### ISSUE TITLE
4.21 Oculus Package Fail get_signature

### ISSUE THREAD

**Issue by Skulltulla** [Skulltulla/IssueTracker#137]
# Dev. Env.
- UE 4.21 (Oculus, Epic Launcher)

# Issue

I get the following error while attempting to package a shipping build that is for distribution for the Oculus Go.

    UATHelper: Packaging (Android (ASTC)):   GetSignatureToken get_signature error: Missing entitlement for AppId (1971031)
    PackagingResults: Error: Missing entitlement for AppId (1971031)
    UATHelper: Packaging (Android (ASTC)):   GetUserID failed: Must call get_signature first (1971051)
    UATHelper: Packaging (Android (ASTC)):   Failed to fetch FBNS credentials from OAF: Must call get_signature first (1971051)
    UATHelper: Packaging (Android (ASTC)):   requestOafRoomUpdate response error: Must call get_signature first (1971051)
    UATHelper: Packaging (Android (ASTC)):   requestOafLaunchDetailsUpdate response error: Must call get_signature first (1971051)
    UATHelper: Packaging (Android (ASTC)):   LogOnlineIdentity: Warning: Oculus: Failed Oculus login. Not currently logged into Oculus.  Make sure Oculus is running and you are entitled to the app.
    PackagingResults: Error: Must call get_signature first (1971051)

Previously, I was able to package and upload a build with UE 4.23 and I did not need to use an OSIG file.

I added the OSIG file, but enabled Remove OSIG Files from Dist. APK. Eventually got a new error:

    UATHelper: Packaging (Android (ASTC)): Z:\app\src\main\java\com\epicgames\ue4\GameActivity.java:2358: error: package com.oculus.svclib does not exist
    UATHelper: Packaging (Android (ASTC)):                             com.oculus.svclib.OVREntitlementChecker.doAutomatedCheck(this);

https://forums.unrealengine.com/development-discussion/vr-ar-development/1440854-missing-oculus-osig-file-from-apk
https://answers.unrealengine.com/questions/489703/android-gear-vr-shipping-distribution-package-fail.html

**Comment by Skulltulla** [comment]
Update - despite the error, with the proper configuration I was able to successfully package a build. I think the error should possible be a warning because it may just be part of code that is executed when a build is being packaged.

**Comment by Skulltulla** [comment]
Disabling v2Signing for Oculus Go / Gear VR APK

**Comment by Skulltulla** [comment]
Conclusion

- A zip version of Android Studio 3.5.3 was downloaded an ran to perform its installation as part of the 4.25 upgrade process:

    D:\ProgramFiles\android-studio-ide-191.6010548-windows\android-studio\bin\studio64.exe

  - Installed
    - SDK Platform: Android 5.0 (Lollipop) API Level 21
    - Android SDK Build-Tools
    - NDK (Side by side) was updated

- Oculus' version of Unreal Engine 4.21 was downloaded for performing a bug fix.
- Visual Studio was completely uninstalled and reinstalled due to a bunch of strange error messages that I don't remember having when I first compiled the engine a long time ago.

**Engine\Plugins\Runtime\Oculus\OculusVR\Source\OculusHMD\OculusMobile_APL.xml**

    // line ~224
    // removed because scvlib no longer exists
    // https://answers.unrealengine.com/questions/489703/android-gear-vr-shipping-distribution-package-fail.html
    // com.oculus.svclib.OVREntitlementChecker.doAutomatedCheck(this);

- AndroidEngine.ini was created:

**Project\Config\Android\AndroidEngine.ini**

    [OnlineSubsystem]
    DefaultPlatformService=Oculus

- DefaultEngine.ini was updated

**Project\Config\DefaultEngine.ini**

    [OnlineSubsystem]
    DefaultPlatformService=Oculus

    [OnlineSubsystemOculus]
    bEnabled=true
    OculusAppId=1234
    RiftAppId=1234
    GearVRAppId=1234

    TargetSDKVersion=23

    PackageForOculusMobile=GearGo
    bRemoveOSIG=True

    KeyStore=keystore.store
    KeyAlias=alias
    KeyStorePassword=password

- DefaultGame.ini was updated

**Project\Config\DefaultGame.ini**

    ForDistribution=True

- ManifestRequirementsOverride.txt was created/updated

**Project\Build\Android\ManifestRequirementsOverride.txt**

    <uses-feature android:name="android.hardware.vr.headtracking" android:required="false" android:version="1"/>

> NOTE: The oculus tool stated that if the app will be shared between GearVR/Go and Quest, then it must be set to false.



Side note, now my keyword is not letting me type into windows search menu.
